const NEWS_REQUEST = 'NEWS_REQUEST';
const NEWS_SUCCESS = 'NEWS_SUCCESS';
const NEWS_FAILURE = 'NEWS_FAILURE';
const CLEAN_STATE = 'CLEAN_STATE';

export {
    NEWS_REQUEST,
    NEWS_SUCCESS,
    NEWS_FAILURE,
    CLEAN_STATE
}